name: Create Pull Request

on:
  push:
    branches:
      - main
      - dev

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Branch Name
        id: branch_name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch_name.outputs.branch }}
          title: ${{ steps.branch_name.outputs.branch }}
          body: Automated pull request created by GitHub Actions
