name: Create Pull Request

on:
  push:
    branches:
      - dev

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.1

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          title: Automatically created pull request
          body: This pull request was automatically created by Github workflow.
          base: main
